### ISSUE TITLE
Practica funciones

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-mayra-diego-daniel-felix#1]
[Practica Mate_Felix.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-mayra-diego-daniel-felix/files/12820624/Practica.Mate_Felix.pdf)

**Comment by 23620031** [comment]
ELEMENTOS DE PORTADA -> 25/25
PROCEDIMIENTO -> 25/25
FIGURAS, ILUSTRACIONES Y FOTOGRAFÍAS -> 25/25
RESULTADOS Y CONCLUCIONES -> 22/25 (faltan la descripción de resultados)

TOTAL=19.4/20

CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
