### ISSUE TITLE
Practica2_Funciones

### ISSUE THREAD

**Issue by Diego0501** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-mayra-diego-daniel-felix#2]
[practica 2_DiegoFidelSosaCruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-mayra-diego-daniel-felix/files/12822599/practica.2_DiegoFidelSosaCruz.pdf)

**Comment by 23620031** [comment]
ELEMENTOS DE PORTADA -> 25/25
PROCEDIMIENTO -> 25/25
FIGURAS, ILUSTRACIONES Y FOTOGRAFÍAS -> 25/25
RESULTADOS Y CONCLUCIONES -> 22/25 (faltan la información de conclusión)

TOTAL=19.4/20

CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
