### ISSUE TITLE
Mayra_Práctica_1AS

### ISSUE THREAD

**Issue by mayraglez917** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-mayra-diego-daniel-felix#4]
[Práctica_Mayra_Glez_1AS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-mayra-diego-daniel-felix/files/12825836/Practica_Mayra_Glez_1AS.pdf)

**Comment by 23620031** [comment]
ELEMENTOS DE PORTADA -> 25/25
PROCEDIMIENTO -> 25/25
FIGURAS, ILUSTRACIONES Y FOTOGRAFÍAS -> 17/25 (cuenta con 4 fotografías)
RESULTADOS Y CONCLUCIONES -> 22/25 (faltan la descripción de resultados)

TOTAL=17.8/20
CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
